name: upload_file_oss
description: 一个简单上传文件到阿里云对象存储OSS的库。
version: 1.0.1
homepage: https://github.com/biner88
repository: https://github.com/biner88/upload_file_oss
issue_tracker: https://github.com/biner88/upload_file_oss/issues

environment:
  sdk: ^3.0.5

dependencies:
  http: ^1.2.2
  crypto: ^3.0.5
  intl: ^0.19.0
  mime: ^1.0.6
dev_dependencies:
  lints: ^4.0.0