name: upload_file_oss
description: A library for simply uploading files to Alibaba Cloud Object Storage OSS.
version: 1.0.4
homepage: https://github.com/biner88
repository: https://github.com/biner88/upload_file_oss
issue_tracker: https://github.com/biner88/upload_file_oss/issues

environment:
  sdk: ^3.0.5

dependencies:
  http: ^1.3.0
  crypto: ^3.0.6
  intl: ^0.20.2
  mime: ^2.0.0
dev_dependencies:
  lints: ^5.1.1